### PR TITLE
feat(functions): add chat completion functions

### PR DESCRIPTION
**Pull request by robswei**
Added chat completion functions from latest openai-node v3.3.0

Ref: https://platform.openai.com/docs/guides/gpt/function-calling

### CODE REVIEW

**Comment by Zakinator123** [comment]
@rtweine2 Just curious, how did you go about generating the new code? Was trying to do the same, and found that the [OpenAI OpenAPI generator](https://github.com/openai/openai-openapi/blob/master/scripts/generate_sdk.py) was generating code that was structured differently than the code in this repo when I changed the OpenAPI generator to use `typescript-fetch`, and there's no instructions in this repo on how to go about generating new code from the latest OpenAPI spec that OpenAI puts out..

**Comment by henrycunh** [comment]
published this PR to `openai-edge-fns` npm package if anyone needs this ASAP

**Comment by dan-kwiat** [comment]
Thanks @rtweine2 !

**Comment by swyxio** [comment]
@Zakinator123 this isnt a complete answer but i think you can just pull it from openai-node https://github.com/openai/openai-node/commit/b7cbca5852b4460e283c2cbed611d641e95c9e81

**Comment by abaybektursun** [comment]
New to react and next.js. How would I extract the function call here?  res does not seem to have it
```
  const res = await openai.createChatCompletion({
    model: 'gpt-4',
    messages: messagesWithSystemPrompt,
    temperature: 0.0,
    stream: true
  })

  // log res
  console.log(res)
  
const stream = OpenAIStream(res, {
    async onCompletion(completion) {
      const title = json.messages[0].content.substring(0, 100)
      const id = json.id ?? nanoid()
      const createdAt = Date.now()
      const path = `/chat/${id}`
      const payload = {
        id,
        title,
        userId,
        createdAt,
        path,
        messages: [
          ...messages,
          {
            content: completion,
            role: 'assistant'
          }
        ]
      }
      await kv.hmset(`chat:${id}`, payload)
      await kv.zadd(`user:chat:${userId}`, {
        score: createdAt,
        member: `chat:${id}`
      })
    }
  })
```

**Pull request merged**
